#include "commands/Clean.hh"
#include <chrono>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

#include <commands/Build.hh>
#include <commands/Command.hh>
#include <helpers.hh>
#include <interface.hh>
#include <objects/ProjectSettings.hh>
#include <objects/Settings.hh>
#include <objects/ZCError.hh>

using namespace std;
namespace fs = std::filesystem;

Build::Build(
    const bool force, const bool quiet, const bool clean, const fs::path &project_root,
    const bool is_zc_build_command
)
    : Command(force, quiet), root_(project_root.empty() ? getProjectRoot() : project_root), clean_(clean),
      is_zc_build_command_(is_zc_build_command),
      p_settings_(ProjectSettings(project_root.empty() ? getProjectRoot() : project_root)),
      g_settings_(GlobalSettings::getInstance()),
      registry_(Registry(project_root.empty() ? getProjectRoot() : project_root))
{
  checkPackageName(p_settings_.name_);
  checkPackageName(p_settings_.target_name_);
}

int Build::operator()()
{
  // CMake configuration
  if (!fs::exists("CMakeLists.txt") || force_)
  {
    log_info("Generating build configuration...");

    generateCMakeLists();
    const string config_cmd = "cmake " + root_.string() + " -B " + root_.string() +
                              "/" BUILD_DIR " -DCMAKE_BUILD_TYPE=Debug" + (quiet_ ? " &>/dev/null" : "");

#ifdef DEBUG_MODE
    log_debug(config_cmd);
#else
    log_info("Configuring project...");
#endif

    if (system(config_cmd.c_str()) != 0)
      throw ZCError(ZC_CMAKE_ERROR, "CMake configuration failed");
  }
  // Build
  const string build_cmd = "cmake --build " + root_.string() + "/" BUILD_DIR + (quiet_ ? " &>/dev/null" : "");

#ifdef DEBUG_MODE
  log_debug(build_cmd);
#else
  log_info("Building project...");
#endif

  if (system(build_cmd.c_str()) != 0)
    throw ZCError(ZC_COMPILATION_ERROR, "Build failed");

  log_success("Project was built successfully in build/");

  if (g_settings_.move_binary_to_current_path_)
  {
    // Move binary to current path to make it easier to execute it
    if (p_settings_.type_ == BIN && is_zc_build_command_)
    {
      fs ::path binary = root_ / BUILD_DIR / p_settings_.target_name_;
      if (fs::exists(binary))
        fs::rename(binary, fs::current_path() / p_settings_.target_name_);
    }
  }

  if (clean_)
  {
    Clean c(false, quiet_, p_settings_, root_);
    c();
  }

  return 0;
}

void Build::generateCMakeLists() const
{
  ofstream cmake(root_ / "CMakeLists.txt");
  if (!cmake.is_open())
    throw ZCError(ZC_WRITING_ERROR, "Could not write CMakeLists.txt");

  // ZC Message
  const auto now = chrono::system_clock::now();
  auto now_sec = chrono::floor<chrono::seconds>(now);
  const string s = format("{:%F %T}", now_sec);
  cmake << "# --- This file was automatically generated by ZC\n";
  cmake << "# --- Date of creation: " << s << " (UTC)\n";
  cmake << "# --- Editing this file manually could break it.\n\n";

  // Boilerplate
  cmake << "cmake_minimum_required(VERSION 3.12)\n";                   // Version
  cmake << "set(CMAKE_EXPORT_COMPILE_COMMANDS ON)\n";                  // Compile commands for clangd
  cmake << "project(" << p_settings_.name_ << " LANGUAGES C CXX)\n\n"; // Project name

  // Variables for local and global ZC directories
  cmake << "set(ZC_LOCAL_ROOT \"${CMAKE_SOURCE_DIR}/" << EXTERNAL << "\")\n";
  cmake << "if(WIN32)\n";
  cmake << "  set(ZC_GLOBAL_ROOT \"$ENV{USERPROFILE}/" << ROOT_DIR << "\")\n";
  cmake << "else()\n";
  cmake << "  set(ZC_GLOBAL_ROOT \"$ENV{HOME}/" << ROOT_DIR << "\")\n";
  cmake << "endif()\n\n";

  // Standards
  if (p_settings_.add_std_)
  {
    cmake << "set(CMAKE_CXX_STANDARD " << (p_settings_.cpp_std_.substr(3)) << ")\n";
    cmake << "set(CMAKE_C_STANDARD " << (p_settings_.c_std_.substr(1)) << ")\n\n";
  }

  // Sources
  vector<string> c_extensions{"c", "cc", "cxx", "cpp"};
  vector<string> h_extensions{"h", "hh", "hxx", "hpp"};

  string src = fs::relative(p_settings_.src_folder_, root_);
  string include = fs::relative(p_settings_.include_folder_, root_);
  for (auto &ext : c_extensions)
    ext = " \"" + src + "/*." + ext + '"';
  for (auto &ext : h_extensions)
    ext = " \"" + include + "/*." + ext + '"';

  cmake << "file(GLOB_RECURSE SOURCES" << join(c_extensions, "") << ")\n";
  cmake << "file(GLOB_RECURSE HEADERS" << join(h_extensions, "") << ")\n\n";

  // Source code
  vector<string> outputs;

  if (p_settings_.type_ == BIN)
  {
    cmake << "add_executable(" << p_settings_.target_name_ << '\n';
    cmake << "  ${SOURCES}\n";
    cmake << "  ${HEADERS}\n";
    cmake << ")\n\n";
    outputs.push_back(p_settings_.target_name_);
  }
  else if (p_settings_.type_ == LIB)
  {
    const string static_target = p_settings_.target_name_ + "_static_target";
    cmake << "add_library(" << static_target << " STATIC\n";
    cmake << "  ${SOURCES}\n";
    cmake << "  ${HEADERS}\n";
    cmake << ")\n\n";
    cmake << "set_target_properties(" << static_target << " PROPERTIES OUTPUT_NAME \""
          << p_settings_.target_name_ << "\")\n\n";
    outputs.push_back(static_target);

    const string shared_target = p_settings_.target_name_ + "_shared_target";
    cmake << "add_library(" << shared_target << " SHARED\n";
    cmake << "  ${SOURCES}\n";
    cmake << "  ${HEADERS}\n";
    cmake << ")\n\n";
    cmake << "set_target_properties(" << shared_target << " PROPERTIES OUTPUT_NAME \""
          << p_settings_.target_name_ << "\")\n\n";
    outputs.push_back(shared_target);
  }

  for (const string &output : outputs)
  {
    // Includes
    cmake << "target_include_directories(" << output << " PRIVATE\n";
    cmake << "  \"${ZC_LOCAL_ROOT}/include\"\n";  // Local include folder
    cmake << "  \"${ZC_GLOBAL_ROOT}/include\"\n"; // Global include folder
    cmake << "  \"${CMAKE_SOURCE_DIR}/" << fs::relative(p_settings_.include_folder_, root_).string()
          << "\"\n"; // Project include folder
    cmake << ")\n\n";

    // Libraries
    if (!registry_.getPackages().empty())
    {
      vector<Package> local_deps;
      vector<Package> global_deps;
      fs::path global_lib_path = getZCRootDir() / LIB_DIR;
      for (const auto pkg : registry_.getPackages())
      {
        if (fs::exists(registry_.getLibPath() / pkg.name_))
          local_deps.push_back(pkg);
        else if (fs::exists(global_lib_path / pkg.name_))
          global_deps.push_back(pkg);
        // Else it's a standard package no need to add a new link path
      }

      cmake << "target_link_directories(" << output << " PRIVATE\n";
      for (const auto dep : global_deps)
        cmake << "  \"${ZC_GLOBAL_ROOT}/lib/" << dep.name_ << "\"\n"; // Global library folders
      for (const auto dep : local_deps)
        cmake << "  \"${ZC_LOCAL_ROOT}/lib/" << dep.name_ << "\"\n"; // Local library folder
      cmake << ")\n\n";

      // Linking dependencies
      cmake << "target_link_libraries(" << output << " PRIVATE\n";
      for (const auto dep : registry_.getPackages())
        cmake << "  " << dep.binary_ << "\n";
      cmake << ")\n\n";
    }

    // Add pthread/dl if UNIX-based
    cmake << "if(UNIX)\n";
    cmake << "  target_link_libraries(" << output << " PRIVATE pthread dl)\n";
    cmake << "endif()\n\n";

    if (p_settings_.static_compile_)
      cmake << "target_link_options(" << output << " PRIVATE \"-static\")\n\n";
  }

  // Activate RPATH
  cmake << "set(CMAKE_SKIP_BUILD_RPATH FALSE)\n";
  cmake << "set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)\n\n";
  cmake << "if(APPLE)\n";
  cmake << "  set(CMAKE_INSTALL_RPATH \"@loader_path/" << EXTERNAL << "/lib;${ZC_GLOBAL_ROOT}/lib\")\n";
  cmake << "else()\n";
  cmake << "  set(CMAKE_INSTALL_RPATH \"$ORIGIN/" << EXTERNAL << "/lib;${ZC_GLOBAL_ROOT}/lib\")\n";
  cmake << "endif()\n";

  cmake.close();
}
