#include <chrono>
#include <filesystem>
#include <fstream>

#include <commands/Build.hh>
#include <commands/Command.hh>
#include <helpers.hh>
#include <interface.hh>
#include <objects/ProjectSettings.hh>
#include <objects/Registry.hh>
#include <objects/Settings.hh>
#include <objects/ZCError.hh>

using namespace std;
namespace fs = std::filesystem;

Build::Build(const bool force, const bool quiet, const bool release_mode)
    : Command(force, quiet), release_mode_(release_mode), registry_(Registry::getInstance()),
      settings_(Settings::getInstance()), project_settings_(ProjectSettings::getInstance())
{
}

int Build::execute()
{
  if (!quiet_)
    info("Scanning sources...");

  scanSources();
  if (sources_.empty())
    throw ZCError(ZC_NO_SOURCE_FILES, "No source files were detected");

  if (project_settings_.getType() == UNDEF)
    throw ZCError(ZC_CONFIG_MISSING_PROPERTY, "The property 'type' is missing");

  if (project_settings_.getType() == BIN)
  {
    if (project_settings_.getExecutableName().empty())
      throw ZCError(ZC_CONFIG_MISSING_PROPERTY, "The property 'executable' is missing");

    if (!fs::exists("CMakeLists.txt") || force_)
    {
      if (!quiet_)
        info("Generating build configuration...");

      generateCMakeLists();
    }

    string root = getProjectRoot().string();
    const string build_type = release_mode_ ? "Release" : "Debug";
    const string config_cmd = "cmake " + root + " -B " + root + "/build -DCMAKE_BUILD_TYPE=" + build_type +
                              (quiet_ ? " &>/dev/null" : "");
    const string build_cmd = "cmake --build " + root + "/build" + (quiet_ ? " &>/dev/null" : "");

    if (!quiet_)
      info("Configuring project...");
    if (system(config_cmd.c_str()) != 0)
      throw ZCError(ZC_CMAKE_ERROR, "CMake configuration failed");

    if (!quiet_)
      info("Building project...");
    if (system(build_cmd.c_str()) != 0)
      throw ZCError(ZC_COMPILATION_ERROR, "Build failed");

    if (!quiet_)
      success("Project was built successfully in build/");
    return 0;
  }
  else
  {
    // TODO : implement library compiling
    throw ZCError();
  }
}

void Build::scanSources()
{
  if (!fs::exists(project_settings_.getSrcFolder()))
    throw ZCError(
        ZC_NOT_FOUND, "The directory " + project_settings_.getSrcFolder().string() + " was not found"
    );
  if (!fs::exists(project_settings_.getIncludeFolder()))
    throw ZCError(
        ZC_NOT_FOUND, "The directory " + project_settings_.getIncludeFolder().string() + " was not found"
    );
  for (const auto &entry : fs::recursive_directory_iterator(project_settings_.getSrcFolder()))
  {
    const auto &path = entry.path();

    bool is_hidden = false;
    for (const auto &part : path)
    {
      if (part.string().front() == '.' && part.string() != "." && part.string() != "..")
      {
        is_hidden = true;
        break;
      }
    }

    if (is_hidden)
      continue;

    File f(path.string());
    if (f.getLanguage() == C || f.getLanguage() == CPP)
      sources_.push_back(f);
  }
}

void Build::generateCMakeLists() const
{
  ofstream cmake(getProjectRoot() / "CMakeLists.txt");
  if (!cmake.is_open())
    throw ZCError(ZC_WRITING_ERROR, "Could not write CMakeLists.txt");

  // ZC Message
  const auto now = chrono::system_clock::now();
  auto now_sec = chrono::floor<chrono::seconds>(now);
  const string s = format("{:%F %T}", now_sec);
  cmake << "# --- This file was automatically generated by ZC\n";
  cmake << "# --- Date of creation: " << s << " (UTC)\n";
  cmake << "# --- Editing this file manually could break it.\n\n";

  // Boilerplate
  cmake << "cmake_minimum_required(VERSION 3.12)\n";
  cmake << "project(" << project_settings_.getName() << " C CXX)\n\n";

  // Standards
  cmake << "set(CMAKE_CXX_STANDARD " << (settings_.getCppStd().substr(3)) << ")\n";
  cmake << "set(CMAKE_C_STANDARD " << (settings_.getCStd().substr(1)) << ")\n\n";

  // Source code
  cmake << "add_executable(" << project_settings_.getExecutableName() << '\n';
  for (const auto &src : sources_)
    cmake << "    " << src.getPath().string() << "\n";
  cmake << ")\n\n";

  // Includes
  cmake << "target_include_directories(" << project_settings_.getExecutableName() << " PRIVATE\n";
  cmake << "    " << project_settings_.getIncludeFolder().string() << "\n";
  cmake << "    " << registry_.getIncludeDir().string() << "\n";
  cmake << ")\n\n";

  // Libraries
  cmake << "target_link_directories(" << project_settings_.getExecutableName() << " PRIVATE\n";
  //  TODO : add local libraries paths
  cmake << "    " << registry_.getLibDir().string() << "\n";
  cmake << ")\n\n";

  // Linking
  // if (!project_settings_.getDeps().empty())
  // {
  //   cmake << "target_link_libraries(" << project_name << " PRIVATE\n";
  //   for (const auto &lib : libs)
  //   {
  //     cmake << "    " << lib << "\n";
  //   }
  //   cmake << ")\n";
  // }

  // Add de pthread/dl if Linux
  // cmake << "if(UNIX)\n";
  // cmake << "    target_link_libraries(" << project_name << " PRIVATE pthread
  // dl)\n"; cmake << "endif()\n";

  cmake << "set(CMAKE_EXPORT_COMPILE_COMMANDS ON)\n";

  cmake.close();
}
