#include <chrono>
#include <filesystem>
#include <fstream>

#include <commands/Build.hh>
#include <commands/Command.hh>
#include <interface.hh>
#include <objects/ProjectSettings.hh>
#include <objects/Registry.hh>
#include <objects/Settings.hh>
#include <objects/ZCError.hh>
#include <sstream>
#include <vector>

using namespace std;
namespace fs = std::filesystem;

Build::Build(const bool force, const bool quiet, const bool release_mode)
    : Command(force, quiet), release_mode_(release_mode), registry_(Registry::getInstance()),
      settings_(Settings::getInstance()), project_settings_(ProjectSettings::getInstance())
{
}

int Build::execute()
{
  if (!quiet_)
    info("Scanning sources...");

  scanSources();
  // Verifications
  if (sources_.empty())
    throw ZCError(ZC_NO_SOURCE_FILES, "No source files were detected");

  if (project_settings_.getType() == UNDEF)
    throw ZCError(ZC_CONFIG_MISSING_PROPERTY, "Property 'type' is missing");

  if (project_settings_.getType() == BIN && project_settings_.getExecutableName().empty())
    throw ZCError(ZC_CONFIG_MISSING_PROPERTY, "Property 'executable' is missing");

  if (project_settings_.getType() == LIB && project_settings_.getSharedLibName().empty() &&
      project_settings_.getStaticLibName().empty())
    throw ZCError(ZC_CONFIG_MISSING_PROPERTY, "Property 'shared' or 'static' is missing");

  // CMake configuration
  if (!fs::exists("CMakeLists.txt") || force_)
  {
    if (!quiet_)
      info("Generating build configuration...");

    generateCMakeLists();

    const string build_type = release_mode_ ? "Release" : "Debug";
    const string config_cmd = "cmake " + root_.string() + " -B " + root_.string() +
                              "/build -DCMAKE_BUILD_TYPE=" + build_type + (quiet_ ? " &>/dev/null" : "");
    if (!quiet_)
      info("Configuring project...");
    if (system(config_cmd.c_str()) != 0)
      throw ZCError(ZC_CMAKE_ERROR, "CMake configuration failed");
  }

  // Build
  const string build_cmd = "cmake --build " + root_.string() + "/build" + (quiet_ ? " &>/dev/null" : "");

  if (!quiet_)
    info("Building project...");
  if (system(build_cmd.c_str()) != 0)
    throw ZCError(ZC_COMPILATION_ERROR, "Build failed");

  if (!quiet_)
    success("Project was built successfully in build/");
  return 0;
}

void Build::scanSources()
{
  if (!fs::exists(project_settings_.getSrcFolder()))
    throw ZCError(
        ZC_NOT_FOUND, "The directory " + project_settings_.getSrcFolder().string() + " was not found"
    );
  if (!fs::exists(project_settings_.getIncludeFolder()))
    throw ZCError(
        ZC_NOT_FOUND, "The directory " + project_settings_.getIncludeFolder().string() + " was not found"
    );
  for (const auto &entry : fs::recursive_directory_iterator(project_settings_.getSrcFolder()))
  {
    const auto &path = entry.path();

    bool is_hidden = false;
    for (const auto &part : path)
    {
      if (part.string().front() == '.' && part.string() != "." && part.string() != "..")
      {
        is_hidden = true;
        break;
      }
    }

    if (is_hidden)
      continue;

    File f(path.string());
    if (f.getLanguage() == C || f.getLanguage() == CPP)
      sources_.push_back(f);
  }
}

void Build::generateCMakeLists() const
{
  ofstream cmake(root_ / "CMakeLists.txt");
  if (!cmake.is_open())
    throw ZCError(ZC_WRITING_ERROR, "Could not write CMakeLists.txt");

  // ZC Message
  const auto now = chrono::system_clock::now();
  auto now_sec = chrono::floor<chrono::seconds>(now);
  const string s = format("{:%F %T}", now_sec);
  cmake << "# --- This file was automatically generated by ZC\n";
  cmake << "# --- Date of creation: " << s << " (UTC)\n";
  cmake << "# --- Editing this file manually could break it.\n\n";

  // Boilerplate
  cmake << "cmake_minimum_required(VERSION 3.12)\n";                   // Version
  cmake << "set(CMAKE_EXPORT_COMPILE_COMMANDS ON)\n";                  // Compile commands for clangd
  cmake << "project(" << project_settings_.getName() << " C CXX)\n\n"; // Project name

  // Variables for local and global ZC directories
  cmake << "set(ZC_LOCAL_ROOT \"${CMAKE_SOURCE_DIR}/" << ZC_MODULES << "\")\n";
  cmake << "if(WIN32)\n";
  cmake << "  set(ZC_GLOBAL_ROOT \"$ENV{USERPROFILE}/" << ROOT_DIR << "\")\n";
  cmake << "else()\n";
  cmake << "  set(ZC_GLOBAL_ROOT \"$ENV{HOME}/" << ROOT_DIR << "\")\n";
  cmake << "endif()\n\n";

  // Standards
  cmake << "set(CMAKE_CXX_STANDARD " << (settings_.getCppStd().substr(3)) << ")\n";
  cmake << "set(CMAKE_C_STANDARD " << (settings_.getCStd().substr(1)) << ")\n\n";

  // Source code
  stringstream sources_list_stream;
  for (const auto &src : sources_)
    sources_list_stream << "  \"${CMAKE_SOURCE_DIR}/" << fs::relative(src.getPath(), root_).string()
                        << "\"\n";

  const string sources_list = sources_list_stream.str();
  vector<string> outputs;

  if (project_settings_.getType() == BIN)
  {
    cmake << "add_executable(" << project_settings_.getExecutableName() << '\n';
    cmake << sources_list;
    cmake << ")\n\n";
    outputs.push_back(project_settings_.getExecutableName());
  }
  else if (project_settings_.getType() == LIB)
  {
    const string static_name = project_settings_.getStaticLibName();
    const string shared_name = project_settings_.getSharedLibName();

    if (!static_name.empty())
    {
      const string static_target = static_name + "_static_target";
      cmake << "add_library(" << static_target << " STATIC\n";
      cmake << sources_list;
      cmake << ")\n\n";
      cmake << "set_target_properties(" << static_target << " PROPERTIES OUTPUT_NAME \"" << static_name
            << "\")\n\n";
      outputs.push_back(static_target);
    }
    if (!shared_name.empty())
    {
      string shared_target = shared_name + "_shared_target";
      cmake << "add_library(" << shared_target << " SHARED\n";
      cmake << sources_list;
      cmake << ")\n\n";
      cmake << "set_target_properties(" << shared_target << " PROPERTIES OUTPUT_NAME \"" << shared_name
            << "\")\n\n";
      outputs.push_back(shared_target);
    }
  }

  for (const string &output : outputs)
  {
    // Includes
    cmake << "target_include_directories(" << output << " PRIVATE\n";
    cmake << "  \"${ZC_LOCAL_ROOT}/include\"\n";  // Local include folder
    cmake << "  \"${ZC_GLOBAL_ROOT}/include\"\n"; // Global include folder
    cmake << "  \"${CMAKE_SOURCE_DIR}/" << fs::relative(project_settings_.getIncludeFolder(), root_).string()
          << "\"\n"; // Project include folder
    cmake << ")\n\n";

    // Libraries
    cmake << "target_link_directories(" << output << " PRIVATE\n";
    cmake << "  \"${ZC_GLOBAL_ROOT}/lib\"\n"; // Global library folder
    cmake << "  \"${ZC_LOCAL_ROOT}/lib\"\n";  // Local library folder
    cmake << ")\n\n";

    // Linking dependencies
    if (!project_settings_.getDeps().empty())
    {
      cmake << "target_link_libraries(" << output << " PRIVATE\n";
      for (const auto &lib : project_settings_.getDeps())
        cmake << "  " << std::get<0>(lib) << "\n";
      cmake << ")\n\n";
    }

    // Add pthread/dl if UNIX-based
    cmake << "if(UNIX)\n";
    cmake << "  target_link_libraries(" << output << " PRIVATE pthread dl)\n";
    cmake << "endif()\n\n";
  }

  // Activate RPATH
  cmake << "set(CMAKE_SKIP_BUILD_RPATH FALSE)\n";
  cmake << "set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)\n\n";
  cmake << "if(APPLE)\n";
  cmake << "  set(CMAKE_INSTALL_PATH \"@loader_path/" << ZC_MODULES << "/lib;${ZC_GLOBAL_ROOT}/lib\")\n";
  cmake << "else()\n";
  cmake << "  set(CMAKE_INSTALL_PATH \"$ORIGIN/" << ZC_MODULES << "/lib;${ZC_GLOBAL_ROOT}/lib\")\n";
  cmake << "endif()\n";

  cmake.close();
}
