#include "Create.h"

#include <chrono>
#include <filesystem>
#include <format>
#include <sstream>
#include <vector>

#include "clang_utils.h"
#include "commands/Command.h"
#include "excepts/ZCException.h"
#include "helpers.h"
#include "Language.h"
#include "templates/TemplateEngine.h"

ZC_DEV_CONFIG

namespace zc
{

Create::Create(
  const bool force, const bool edit, std::vector<std::string> &files,
  const std::vector<std::string> &input_files
)
  : Command(force), edit_(edit)
{
  for (CAA f : files)
  {
    if (!force_ && fs::exists(f) &&
        !if_.ask("The file '" + f + "' already exists. Do you want to replace it ?"))
    {
      if_.info("Skipped file " + f);
      continue;
    }
    Language l = language_of(f);
    if (files_.contains(l))
      files_.at(l).push_back(f);
    else
      files_[l] = { f };
  }
  for (CAA f : input_files)
  {
    if (!fs::exists(f))
      throw ZCException(ZCE_NOT_FOUND, "Input file " + f + " not found.");
    Language l = language_of(f);
    if (input_files_.contains(l))
      input_files_.at(l).push_back(f);
    else
      input_files_[l] = { f };
  }
}

void Create::operator()()
{
  for (CAA[lang, files] : files_)
  {
    switch (lang)
    {
    case H:
      if (input_files_.contains(C))
      {
        get_declarations(C);
        for (CAA f : files)
        {
          try
          {
            write_declarations(f, C);
            files_to_edit_.push_back(f);
          }
          catch (const ZCException &)
          {
            continue;
          }
        }
      }
      break;
    case HXX:
      if (input_files_.contains(CXX))
      {
        get_declarations(CXX);
        for (CAA f : files)
        {
          try
          {
            write_declarations(f, CXX);
            files_to_edit_.push_back(f);
          }
          catch (const ZCException &)
          {
            continue;
          }
        }
      }
      break;
    default:
      for (CAA f : files)
        if (te_.init_with_template(f, lang, force_))
          files_to_edit_.push_back(f);
      break;
    }
  }

  if ((gc_.open_after_create || edit_) && !files_to_edit_.empty())
  {
    stringstream cmd;
    cmd << gc_.editor;
    for (const auto &f : files_to_edit_)
      cmd << " " << escape_shell_arg(f);
    const int result = system(cmd.str().c_str());
  }
}

void Create::get_declarations(const Language l)
{
  for (CAA file : input_files_.at(l))
  {
    Declarations d = parse_declarations(file);
    merge_declarations(d, l);
  }
}

void Create::merge_declarations(const Declarations &src, Language dest)
{
  Declarations &d = declarations_[dest];
  merge(src.includes, d.includes);
  merge(src.macros, d.macros);
  merge(src.typedefs, d.typedefs);
  merge(src.enums, d.enums);
  merge(src.structs, d.structs);
  merge(src.unions, d.unions);
  merge(src.globals, d.globals);
  merge(src.functions, d.functions);
}

void Create::write_declarations(const std::filesystem::path &f, const Language l) const
{
  stringstream content;
  Declarations decls = declarations_.at(l);

  // Custom header
  const string s = std::format("{:%F %T}", chrono::floor<chrono::seconds>(chrono::system_clock::now()));
  content << "// --- This file was automatically generated by ZC\n";
  content << "// --- Date of creation: " << s << " (UTC)\n";

  // Header guard
  content << "#pragma once\n\n";

  if (!decls.includes.empty())
  {
    content << "/* Includes */\n";
    for (const auto &inc : decls.includes)
      content << inc;
    content << '\n';
  }

  if (!decls.macros.empty())
  {
    content << "/* Macros */\n";
    for (const auto &macro : decls.macros)
      content << "#define " << macro << '\n';
    content << '\n';
  }

  if (l == C)
    content << "#ifdef __cplusplus\n"
            << "extern \"C\"\n"
            << "{\n"
            << "#endif\n\n";

  if (!decls.enums.empty())
  {
    content << "/* Enums */\n";
    for (const auto &en : decls.enums)
      content << en << ";\n\n";
  }

  if (!decls.unions.empty())
  {
    content << "/* Unions */\n";
    for (const auto &un : decls.unions)
      content << un << ";\n\n";
  }

  if (!decls.structs.empty())
  {
    content << "/* Structures */\n";
    for (const auto &struc : decls.structs)
      content << struc << ";\n\n";
  }

  if (!decls.typedefs.empty())
  {
    content << "/* Typedefs */\n";
    for (const auto &td : decls.typedefs)
      content << td << ";\n\n";
  }

  if (!decls.globals.empty())
  {
    content << "/* Global variables */\n";
    for (const auto &glob : decls.globals)
      content << glob << ";\n";
    content << '\n';
  }

  if (!decls.functions.empty())
  {
    content << "/* Functions */\n";
    for (const auto &func : decls.functions)
      content << func << ";\n";
    content << '\n';
  }

  if (l == C)
    content << "#ifdef __cplusplus\n"
            << "}\n"
            << "#endif\n";

  write_file(f, content.str());
}

} // namespace zc
