#include <chrono>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

#include "helpers.hh"
#include "interface.hh"
#include "nlohmann/json.hpp"
#include "objects/Configs/LocalConfig.hh"
#include "objects/Controllers/Controller.hh"
#include "objects/Controllers/GlobalController.hh"
#include "objects/Controllers/LocalController.hh"
#include "objects/Registries/LocalRegistry.hh"
#include "objects/Registries/Registry.hh"
#include "objects/ZCError.hh"

using namespace std;
namespace fs = std::filesystem;

LocalController::LocalController(Logger log, bool force, const std::filesystem::path &root)
    : Controller(log, force, root), build_dir_(root_dir_ / BUILD_DIR), cmakelists_(root_dir_ / CMAKELISTS)
{
  bin_dir_ = root_dir_ / EXTERNAL / BIN_DIR;
  lib_dir_ = root_dir_ / EXTERNAL / LIB_DIR;
  include_dir_ = root_dir_ / EXTERNAL / INCLUDE_DIR;

  auto local_config = std::make_unique<LocalConfig>(root_dir_ / CONFIG);
  lc_ = local_config.get();
  c_ = std::move(local_config);
  r_ = std::make_unique<LocalRegistry>(root_dir_ / REGISTRY);

  checkPackageName(lc_->name_);
  checkPackageName(lc_->target_);
  checkFolderNames();
}

void LocalController::cleanProject()
{
  if (fs::exists(cmakelists_) && fs::is_regular_file(cmakelists_))
    if (fs::remove(cmakelists_))
      log_(LogLevel::INFO, "Cleaned " + cmakelists_.filename().string());

  if (fs::exists(root_dir_ / ".cache") && fs::is_directory(root_dir_ / ".cache"))
    if (fs::remove_all(root_dir_ / ".cache") > 0)
      log_(LogLevel::INFO, "Cleaned .cache/");

  if ((lc_->type_ == Type::BIN || force_) && fs::exists(build_dir_) && fs::is_directory(build_dir_))
    if (fs::remove_all(build_dir_) > 0)
      log_(LogLevel::INFO, "Cleaned " + build_dir_.filename().string());
}

void LocalController::buildProject(bool quiet, bool release_mode)
{
  GlobalController g(log_, force_);
  buildProject(quiet, release_mode, g.gc_->flags_);
}

void LocalController::buildProject(
    bool quiet, bool release_mode, const std::vector<std::string> &compile_options
)
{
  if (fs::exists(build_dir_) && force_)
    cleanProject();

  const char *quiet_cmd = (quiet ? " &>/dev/null" : "");
  // CMake configuration
  if (!fs::exists(cmakelists_) || force_)
  {
    log_(LogLevel::INFO, "Generating build configuration...");

    generateCMakeLists(compile_options);
    const string config_cmd = "cmake " + escape_shell_arg(root_dir_.string()) + " -B " +
                              escape_shell_arg(build_dir_.string()) +
                              " -DCMAKE_BUILD_TYPE=" + (release_mode ? "Release " : "Debug ") + quiet_cmd;

#ifdef DEBUG_MODE
    log_(LogLevel::DEBUG, config_cmd);
#else
    log_(LogLevel::INFO, "Configuring project...");
#endif

    if (system(config_cmd.c_str()) != 0)
      throw ZCError(ZC_CMAKE_ERROR, "CMake configuration failed");
  }
  // Build
  const string build_cmd = "cmake --build " + escape_shell_arg(build_dir_.string()) + quiet_cmd;

#ifdef DEBUG_MODE
  log_(LogLevel::DEBUG, build_cmd);
#else
  log_(LogLevel::INFO, "Building project...");
#endif

  if (system(build_cmd.c_str()) != 0)
    throw ZCError(ZC_COMPILATION_ERROR, "Build failed");

  log_(LogLevel::SUCCESS, "Project was built successfully in " + build_dir_.string());
}

void LocalController::generateCMakeLists(const std::vector<std::string> &compile_options) const
{
  ofstream cmake(cmakelists_);
  if (!cmake.is_open())
    throw ZCError(ZC_WRITING_ERROR, "Could not write CMakeLists.txt");

  // ZC Message
  const auto now = chrono::system_clock::now();
  auto now_sec = chrono::floor<chrono::seconds>(now);
  const string s = format("{:%F %T}", now_sec);
  cmake << "# --- This file was automatically generated by ZC\n";
  cmake << "# --- Date of creation: " << s << " (UTC)\n";
  cmake << "# --- Editing this file manually could break it.\n\n";

  // Boilerplate
  cmake << "cmake_minimum_required(VERSION 3.12)\n";  // Version
  cmake << "set(CMAKE_EXPORT_COMPILE_COMMANDS ON)\n"; // Compile commands for clangd
  cmake << "project(" << lc_->name_ << " LANGUAGES";  // Project name
  for (const auto &language : lc_->languages_) cmake << " " << upper(language);
  cmake << ")\n\n";

  // Variables for local and global ZC directories
  cmake << "set(ZC_LOCAL_ROOT \"${CMAKE_SOURCE_DIR}/" << EXTERNAL << "\")\n";
  cmake << "if(WIN32)\n";
  cmake << "  set(ZC_GLOBAL_ROOT \"$ENV{USERPROFILE}/" << ROOT_DIR << "\")\n";
  cmake << "else()\n";
  cmake << "  set(ZC_GLOBAL_ROOT \"$ENV{HOME}/" << ROOT_DIR << "\")\n";
  cmake << "endif()\n\n";

  // Standards
  if (lc_->add_std_)
  {
    cmake << "set(CMAKE_CXX_STANDARD " << (lc_->cpp_std_.substr(3)) << ")\n";
    cmake << "set(CMAKE_C_STANDARD " << (lc_->c_std_.substr(1)) << ")\n\n";
  }

  // Compile options
  if (!compile_options.empty())
  {
    cmake << "add_compile_options(\n";
    for (const auto &flag : compile_options) cmake << "  " << flag << "\n";
    cmake << ")\n\n";
  }

  // Macro definitions for debug/release mode
  cmake << "if(CMAKE_BUILD_TYPE STREQUAL \"Debug\")\n";
  cmake << "  add_definitions(-DZC_DEBUG)\n";
  cmake << "else()\n";
  cmake << "  add_definitions(-DZC_RELEASE)\n";
  cmake << "endif()\n\n";

  // Sources (make sure the paths are relative to the root of the project)
  fs::path src = fs::relative(root_dir_ / lc_->src_folder_, root_dir_);
  fs::path include = fs::relative(root_dir_ / lc_->include_folder_, root_dir_);

  vector<string> c_extensions{"c", "cc", "cxx", "cpp"};
  vector<string> h_extensions{"h", "hh", "hxx", "hpp"};
  for (auto &ext : c_extensions) ext = " \"" + src.string() + "/*." + ext + '"';
  for (auto &ext : h_extensions) ext = " \"" + include.string() + "/*." + ext + '"';
  cmake << "file(GLOB_RECURSE SOURCES" << join(c_extensions, "") << ")\n";
  cmake << "file(GLOB_RECURSE HEADERS" << join(h_extensions, "") << ")\n\n";

  // Source code
  vector<string> outputs;

  if (lc_->type_ == Type::BIN)
  {
    cmake << "add_executable(" << lc_->target_ << '\n';
    cmake << "  ${SOURCES}\n";
    cmake << "  ${HEADERS}\n";
    cmake << ")\n\n";
    outputs.push_back(lc_->target_);
  }
  else if (lc_->type_ == Type::LIB)
  {
    const string static_target = lc_->target_ + "_static_target";
    cmake << "add_library(" << static_target << " STATIC\n";
    cmake << "  ${SOURCES}\n";
    cmake << "  ${HEADERS}\n";
    cmake << ")\n\n";
    cmake << "set_target_properties(" << static_target << " PROPERTIES OUTPUT_NAME \"" << lc_->target_
          << "\")\n\n";
    outputs.push_back(static_target);

    const string shared_target = lc_->target_ + "_shared_target";
    cmake << "add_library(" << shared_target << " SHARED\n";
    cmake << "  ${SOURCES}\n";
    cmake << "  ${HEADERS}\n";
    cmake << ")\n\n";
    cmake << "set_target_properties(" << shared_target << " PROPERTIES OUTPUT_NAME \"" << lc_->target_
          << "\")\n\n";
    outputs.push_back(shared_target);
  }

  for (const string &output : outputs)
  {
    // Includes
    cmake << "target_include_directories(" << output << " PRIVATE\n";
    cmake << "  \"${ZC_LOCAL_ROOT}/include\"\n";                                    // Local include folder
    cmake << "  \"${ZC_GLOBAL_ROOT}/include\"\n";                                   // Global include folder
    cmake << "  \"${CMAKE_SOURCE_DIR}/" << lc_->include_folder_.string() << "\"\n"; // Project include folder
    cmake << ")\n\n";

    // Libraries
    if (!r_->getPackages().empty())
    {
      vector<Package> local_deps;
      vector<Package> global_deps;
      fs::path global_lib_path = getZCRootDir() / LIB_DIR;
      for (const auto pkg : r_->getPackages())
      {
        if (fs::exists(lib_dir_ / pkg.name))
          local_deps.push_back(pkg);
        else if (fs::exists(global_lib_path / pkg.name))
          global_deps.push_back(pkg);
        // Else it's a standard package no need to add a new link path
      }

      cmake << "target_link_directories(" << output << " PRIVATE\n";
      for (const auto dep : global_deps)
        cmake << "  \"${ZC_GLOBAL_ROOT}/lib/" << dep.name << "\"\n"; // Global library folders
      for (const auto dep : local_deps)
        cmake << "  \"${ZC_LOCAL_ROOT}/lib/" << dep.name << "\"\n"; // Local library folder
      cmake << ")\n\n";

      // Linking dependencies
      cmake << "target_link_libraries(" << output << " PRIVATE\n";
      for (const auto dep : r_->getPackages()) cmake << "  " << dep.binary << "\n";
      cmake << ")\n\n";
    }

    // Add pthread/dl if UNIX-based
    cmake << "if(UNIX)\n";
    cmake << "  target_link_libraries(" << output << " PRIVATE pthread dl)\n";
    cmake << "endif()\n\n";

    if (lc_->static_compile_)
      cmake << "target_link_options(" << output << " PRIVATE \"-static\")\n\n";
  }

  // Activate RPATH
  cmake << "set(CMAKE_SKIP_BUILD_RPATH FALSE)\n";
  cmake << "set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)\n\n";
  cmake << "if(APPLE)\n";
  cmake << "  set(CMAKE_INSTALL_RPATH \"@loader_path/" EXTERNAL "/lib;${ZC_GLOBAL_ROOT}/lib\")\n";
  cmake << "else()\n";
  cmake << "  set(CMAKE_INSTALL_RPATH \"$ORIGIN/" EXTERNAL "/lib;${ZC_GLOBAL_ROOT}/lib\")\n";
  cmake << "endif()\n";

  cmake.close();
}

void LocalController::publishProject()
{
  log_(
      LogLevel::INFO, "Preparing to publish package '" + lc_->name_ + "' v" + lc_->version_->string() + "..."
  );
  if (lc_->name_.empty() || lc_->author_.empty() || !lc_->version_)
    throw ZCError(ZC_CONFIG_MISSING_PROPERTY, "Project name, author, or version is missing in zc.json");

  log_(LogLevel::WARNING, "This action is irreversible");

  GlobalController gc(log_, force_);
  std::string token = gc.gc_->token_;
  if (token.empty())
    throw ZCError(ZC_EMPTY_TOKEN, "Authentication error: token is empty. Please run 'zc login' first.");

  // 0. Verify identity: authenticated user must match project author
  log_(LogLevel::INFO, "Verifying GitHub identity...");
  try
  {
    string user_info_raw = net_.getAuth("https://api.github.com/user", token);
    auto user_info = nlohmann::json::parse(user_info_raw);
    string github_login = user_info["login"];

    if (github_login != lc_->author_)
    {
      throw ZCError(
          ZC_AUTHENTICATION_ERROR, "Identity mismatch: You are logged in as '" + github_login +
                                       "' but the author in zc.json is '" + lc_->author_ +
                                       "'. Publication blocked for security reasons."
      );
    }
    log_(LogLevel::SUCCESS, "Authenticated as " + github_login);
  }
  catch (const ZCError &e)
  {
    if (e.code() == ZC_AUTHENTICATION_ERROR)
      throw;
    throw ZCError(ZC_AUTHENTICATION_ERROR, "Failed to verify GitHub identity. Your token might be expired.");
  }

  string tag = "v" + lc_->version_->string();
  string archive_url =
      "https://github.com/" + lc_->author_ + "/" + lc_->name_ + "/archive/refs/tags/" + tag + ".tar.gz";

  log_(LogLevel::INFO, "Expected archive URL: " + archive_url);
  const fs::path archive_path = tmp_dir_ / (lc_->name_ + "_" + tag + ".tar.gz");
  fs::create_directories(tmp_dir_);

  // 1. Ensure the release exists on GitHub
  string release_api_url =
      "https://api.github.com/repos/" + lc_->author_ + "/" + lc_->name_ + "/releases/tags/" + tag;

  bool release_exists = false;
  try
  {
    log_(LogLevel::DEBUG, "Checking if release '" + tag + "' exists on GitHub...");
    net_.getAuth(release_api_url, token);
    release_exists = true;
    log_(LogLevel::SUCCESS, "Release " + tag + " found!");
  }
  catch (const ZCError &)
  {
    log_(LogLevel::WARNING, "Release " + tag + " not found. Attempting to create it...");

    if (!ask("Do you want to create tag " + tag + "?"))
      return;

    nlohmann::json release_payload;
    release_payload["tag_name"] = tag;
    release_payload["name"] = "Release " + tag;
    release_payload["body"] = "Automated release by ZC build tool.";
    release_payload["generate_release_notes"] = true;

    string create_release_url =
        "https://api.github.com/repos/" + lc_->author_ + "/" + lc_->name_ + "/releases";

    try
    {
      net_.postAuth(create_release_url, release_payload.dump(), token);
      log_(LogLevel::SUCCESS, "Release " + tag + " created successfully!");
    }
    catch (const ZCError &err)
    {
      throw ZCError(
          ZC_NETWORK_ERROR, "Failed to create release. Ensure the tag exists or you have enough permissions."
      );
    }
  }

  // 2. Download and Hash
  log_(LogLevel::INFO, "Downloading archive for verification...");
  try
  {
    net_.download(archive_url, archive_path);
  }
  catch (const ZCError &e)
  {
    throw ZCError(
        ZC_NETWORK_ERROR, "Failed to download the archive from GitHub. Check your internet connection."
    );
  }

  string sha256 = calculate_sha256(archive_path);
  log_(LogLevel::SUCCESS, "SHA-256 calculated: " + sha256);
  fs::remove(archive_path);

  // 3. Upload Recipe to Registry
  nlohmann::json recipe;
  recipe["name"] = lc_->name_;
  recipe["version"] = lc_->version_->string();
  recipe["url"] = archive_url;
  recipe["sha256"] = sha256;
  recipe["owner"] = lc_->author_;

  string file_path = "packages/" + lc_->name_ + "/" + lc_->version_->string() + ".json";
  nlohmann::json payload;
  payload["message"] = "Publish " + lc_->name_ + " v" + lc_->version_->string();
  payload["content"] = base64_encode(recipe.dump(2));

  string api_url = "https://api.github.com/repos/" GH_REPO "/contents/" + file_path;

  log_(LogLevel::INFO, "Uploading recipe to registry...");
  try
  {
    // 3.1 Safety Check: Ensure the package owner doesn't change
    string package_dir_url = "https://api.github.com/repos/" GH_REPO "/contents/packages/" + lc_->name_;
    try
    {
      log_(LogLevel::DEBUG, "Verifying package ownership in registry...");
      string dir_content_raw = net_.getAuth(package_dir_url, token);
      auto dir_content = nlohmann::json::parse(dir_content_raw);

      if (dir_content.is_array() && !dir_content.empty())
      {
        // Get the first file found to check the original owner
        string first_version_url = dir_content[0]["download_url"];
        string first_version_raw = net_.getAuth(first_version_url, token);
        auto first_version_json = nlohmann::json::parse(first_version_raw);

        if (first_version_json.contains("owner") && first_version_json["owner"] != lc_->author_)
        {
          throw ZCError(
              ZC_AUTHENTICATION_ERROR, "Security Violation: This package is owned by '" +
                                           first_version_json["owner"].get<string>() +
                                           "'. You cannot publish a new version."
          );
        }
      }
    }
    catch (const ZCError &e)
    {
      // 404 is fine, it means it's a new package
      if (string(e.what()).find("404") == string::npos)
        throw;
    }

    // 3.2 Upload the recipe
    net_.put(api_url, payload.dump(), token);
    log_(LogLevel::SUCCESS, "Your package has been successfully published to the registry!");
  }
  catch (const ZCError &e)
  {
    if (string(e.what()).find("422") != string::npos)
    {
      throw ZCError(
          ZC_NETWORK_ERROR, "Version " + lc_->version_->string() + " already exists in the registry."
      );
    }
    throw ZCError(ZC_NETWORK_ERROR, "Failed to upload recipe: " + string(e.what()));
  }
}

bool LocalController::addDependency(const std::string &target)
{
  GlobalController g(log_, force_);
  Package p;

  if (isInstalled(target) && !force_)
  {
    log_(LogLevel::WARNING, "Skipped package '" + target + "' already installed locally.");
    return false;
  }
  else
  {
    try
    {
      p = g.getPackage(target);
      p.is_installed_locally = false;
      r_->indexPackage(p);
      log_(LogLevel::SUCCESS, "Added dependency: " + p.name);
      return true;
    }
    catch (const ZCError &z)
    {
      log_(LogLevel::ERROR, "Skipped package '" + target + "' not installed globally.");
      return false;
    }
  }
}

void LocalController::checkFolderNames() const
{
  if (!fs::exists(root_dir_ / lc_->src_folder_))
    throw ZCError(
        ZC_CONFIG_CONTENT_ERROR, "Source folder '" + lc_->src_folder_.string() + "' does not exist"
    );

  if (!fs::exists(root_dir_ / lc_->include_folder_))
    throw ZCError(
        ZC_CONFIG_CONTENT_ERROR, "Include folder '" + lc_->include_folder_.string() + "' does not exist"
    );

  vector<string> invalid_names{"external", "build", ".cache", "CMakeLists.txt", "registry.json", "zc.json"};

  string src_str = lc_->src_folder_.filename().string();
  string inc_str = lc_->include_folder_.filename().string();

  bool is_src_invalid = ranges::find(invalid_names, src_str) != invalid_names.end();
  bool is_inc_invalid = ranges::find(invalid_names, inc_str) != invalid_names.end();

  if (is_src_invalid)
    throw ZCError(ZC_CONFIG_CONTENT_ERROR, "Source folder has a forbidden name");

  if (is_inc_invalid)
    throw ZCError(ZC_CONFIG_CONTENT_ERROR, "Include folder has a forbidden name");
}
