#include <chrono>
#include <filesystem>
#include <fstream>
#include <string>

#include "interface.hh"
#include "nlohmann/json.hpp"
#include "objects/Configs/LocalConfig.hh"
#include "objects/Controllers/Controller.hh"
#include "objects/Controllers/GlobalController.hh"
#include "objects/Controllers/LocalController.hh"
#include "objects/Registries/LocalRegistry.hh"
#include "objects/Registries/Registry.hh"
#include "objects/ZCError.hh"

using namespace std;
namespace fs = std::filesystem;

LocalController::LocalController(Logger log, bool force, const std::filesystem::path &root)
    : Controller(log, force, root), build_dir_(root_dir_ / BUILD_DIR), cmakelists_(root_dir_ / CMAKELISTS)
{
  bin_dir_ = root_dir_ / EXTERNAL / BIN_DIR;
  lib_dir_ = root_dir_ / EXTERNAL / LIB_DIR;
  include_dir_ = root_dir_ / EXTERNAL / INCLUDE_DIR;

  lc_ = new LocalConfig(root_dir_ / CONFIG);
  c_ = lc_;
  r_ = new LocalRegistry(root_dir_ / REGISTRY);

  checkPackageName(lc_->name_);
  checkPackageName(lc_->target_);
  checkFolderNames();
}

void LocalController::cleanProject()
{
  if (fs::exists(cmakelists_) && fs::is_regular_file(cmakelists_))
    if (fs::remove(cmakelists_))
      log_(LogLevel::INFO, "Cleaned " + cmakelists_.filename().string());

  if (fs::exists(root_dir_ / ".cache") && fs::is_directory(root_dir_ / ".cache"))
    if (fs::remove_all(root_dir_ / ".cache") > 0)
      log_(LogLevel::INFO, "Cleaned .cache/");

  if ((lc_->type_ == Type::BIN || force_) && fs::exists(build_dir_) && fs::is_directory(build_dir_))
    if (fs::remove_all(build_dir_) > 0)
      log_(LogLevel::INFO, "Cleaned " + build_dir_.filename().string());
}

void LocalController::buildProject(bool quiet)
{
  if (fs::exists(build_dir_) && force_)
    cleanProject();

  const char *quiet_cmd = (quiet ? " &/dev/null" : "");
  // CMake configuration
  if (!fs::exists(cmakelists_) || force_)
  {
    log_(LogLevel::INFO, "Generating build configuration...");

    generateCMakeLists();
    const string config_cmd = "cmake " + root_dir_.string() + " -B " + build_dir_.string() +
                              " -DCMAKE_BUILD_TYPE=Debug" + quiet_cmd;

#ifdef DEBUG_MODE
    log_(LogLevel::DEBUG, config_cmd);
#else
    log_(LogLevel::INFO, "Configuring project...");
#endif

    if (system(config_cmd.c_str()) != 0)
      throw ZCError(ZC_CMAKE_ERROR, "CMake configuration failed");
  }
  // Build
  const string build_cmd = "cmake --build " + build_dir_.string() + quiet_cmd;

#ifdef DEBUG_MODE
  log_(LogLevel::DEBUG, build_cmd);
#else
  log_(LogLevel::INFO, "Building project...");
#endif

  if (system(build_cmd.c_str()) != 0)
    throw ZCError(ZC_COMPILATION_ERROR, "Build failed");

  log_(LogLevel::SUCCESS, "Project was built successfully in " + build_dir_.string());
}

void LocalController::generateCMakeLists() const
{
  ofstream cmake(cmakelists_);
  if (!cmake.is_open())
    throw ZCError(ZC_WRITING_ERROR, "Could not write CMakeLists.txt");

  // ZC Message
  const auto now = chrono::system_clock::now();
  auto now_sec = chrono::floor<chrono::seconds>(now);
  const string s = format("{:%F %T}", now_sec);
  cmake << "# --- This file was automatically generated by ZC\n";
  cmake << "# --- Date of creation: " << s << " (UTC)\n";
  cmake << "# --- Editing this file manually could break it.\n\n";

  // Boilerplate
  cmake << "cmake_minimum_required(VERSION 3.12)\n";            // Version
  cmake << "set(CMAKE_EXPORT_COMPILE_COMMANDS ON)\n";           // Compile commands for clangd
  cmake << "project(" << lc_->name_ << " LANGUAGES C CXX)\n\n"; // Project name

  // Variables for local and global ZC directories
  cmake << "set(ZC_LOCAL_ROOT \"${CMAKE_SOURCE_DIR}/" << EXTERNAL << "\")\n";
  cmake << "if(WIN32)\n";
  cmake << "  set(ZC_GLOBAL_ROOT \"$ENV{USERPROFILE}/" << ROOT_DIR << "\")\n";
  cmake << "else()\n";
  cmake << "  set(ZC_GLOBAL_ROOT \"$ENV{HOME}/" << ROOT_DIR << "\")\n";
  cmake << "endif()\n\n";

  // Standards
  if (lc_->add_std_)
  {
    cmake << "set(CMAKE_CXX_STANDARD " << (lc_->cpp_std_.substr(3)) << ")\n";
    cmake << "set(CMAKE_C_STANDARD " << (lc_->c_std_.substr(1)) << ")\n\n";
  }

  // Sources
  fs::path src = fs::relative(root_dir_ / lc_->src_folder_, root_dir_);
  if (!fs::exists(src))
    throw ZCError(ZC_NO_SOURCE_FILES, src.string() + " folder does not exist.");

  fs::path include = fs::relative(root_dir_ / lc_->include_folder_, root_dir_);
  if (!fs::exists(include))
    throw ZCError(ZC_NOT_FOUND, include.string() + " folder does not exist.");

  vector<string> c_extensions{"c", "cc", "cxx", "cpp"};
  vector<string> h_extensions{"h", "hh", "hxx", "hpp"};
  for (auto &ext : c_extensions) ext = " \"" + src.string() + "/*." + ext + '"';
  for (auto &ext : h_extensions) ext = " \"" + include.string() + "/*." + ext + '"';
  cmake << "file(GLOB_RECURSE SOURCES" << join(c_extensions, "") << ")\n";
  cmake << "file(GLOB_RECURSE HEADERS" << join(h_extensions, "") << ")\n\n";

  // Source code
  vector<string> outputs;

  if (lc_->type_ == Type::BIN)
  {
    cmake << "add_executable(" << lc_->target_ << '\n';
    cmake << "  ${SOURCES}\n";
    cmake << "  ${HEADERS}\n";
    cmake << ")\n\n";
    outputs.push_back(lc_->target_);
  }
  else if (lc_->type_ == Type::LIB)
  {
    const string static_target = lc_->target_ + "_static_target";
    cmake << "add_library(" << static_target << " STATIC\n";
    cmake << "  ${SOURCES}\n";
    cmake << "  ${HEADERS}\n";
    cmake << ")\n\n";
    cmake << "set_target_properties(" << static_target << " PROPERTIES OUTPUT_NAME \"" << lc_->target_
          << "\")\n\n";
    outputs.push_back(static_target);

    const string shared_target = lc_->target_ + "_shared_target";
    cmake << "add_library(" << shared_target << " SHARED\n";
    cmake << "  ${SOURCES}\n";
    cmake << "  ${HEADERS}\n";
    cmake << ")\n\n";
    cmake << "set_target_properties(" << shared_target << " PROPERTIES OUTPUT_NAME \"" << lc_->target_
          << "\")\n\n";
    outputs.push_back(shared_target);
  }

  for (const string &output : outputs)
  {
    // Includes
    cmake << "target_include_directories(" << output << " PRIVATE\n";
    cmake << "  \"${ZC_LOCAL_ROOT}/include\"\n";                                    // Local include folder
    cmake << "  \"${ZC_GLOBAL_ROOT}/include\"\n";                                   // Global include folder
    cmake << "  \"${CMAKE_SOURCE_DIR}/" << lc_->include_folder_.string() << "\"\n"; // Project include folder
    cmake << ")\n\n";

    // Libraries
    if (!r_->getPackages().empty())
    {
      vector<Package> local_deps;
      vector<Package> global_deps;
      fs::path global_lib_path = getZCRootDir() / LIB_DIR;
      for (const auto pkg : r_->getPackages())
      {
        if (fs::exists(lib_dir_ / pkg.name))
          local_deps.push_back(pkg);
        else if (fs::exists(global_lib_path / pkg.name))
          global_deps.push_back(pkg);
        // Else it's a standard package no need to add a new link path
      }

      cmake << "target_link_directories(" << output << " PRIVATE\n";
      for (const auto dep : global_deps)
        cmake << "  \"${ZC_GLOBAL_ROOT}/lib/" << dep.name << "\"\n"; // Global library folders
      for (const auto dep : local_deps)
        cmake << "  \"${ZC_LOCAL_ROOT}/lib/" << dep.name << "\"\n"; // Local library folder
      cmake << ")\n\n";

      // Linking dependencies
      cmake << "target_link_libraries(" << output << " PRIVATE\n";
      for (const auto dep : r_->getPackages()) cmake << "  " << dep.binary << "\n";
      cmake << ")\n\n";
    }

    // Add pthread/dl if UNIX-based
    cmake << "if(UNIX)\n";
    cmake << "  target_link_libraries(" << output << " PRIVATE pthread dl)\n";
    cmake << "endif()\n\n";

    if (lc_->static_compile_)
      cmake << "target_link_options(" << output << " PRIVATE \"-static\")\n\n";
  }

  // Activate RPATH
  cmake << "set(CMAKE_SKIP_BUILD_RPATH FALSE)\n";
  cmake << "set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)\n\n";
  cmake << "if(APPLE)\n";
  cmake << "  set(CMAKE_INSTALL_RPATH \"@loader_path/" EXTERNAL "/lib;${ZC_GLOBAL_ROOT}/lib\")\n";
  cmake << "else()\n";
  cmake << "  set(CMAKE_INSTALL_RPATH \"$ORIGIN/" EXTERNAL "/lib;${ZC_GLOBAL_ROOT}/lib\")\n";
  cmake << "endif()\n";

  cmake.close();
}

void LocalController::publishProject()
{
  log_(
      LogLevel::INFO, "Preparing to publish package '" + lc_->name_ + "' v" + lc_->version_->string() + "..."
  );

  string archive_url = input("Enter the public URL of your .tar.gz archive (e.g., GitHub Release): ");

  const fs::path archive_path = tmp_dir_ / "temp_publish.tar.gz";
  fs::create_directories(tmp_dir_);

  log_(LogLevel::INFO, "Downloading archive to calculate SHA-256 hash...");

  // Download user archive
  net_.download(archive_url, archive_path);

  // Calculate archive hash
  string sha256 = "";
  try
  {
    string hash_cmd = "shasum -a 256 " + escape_shell_arg(archive_path.string()) + " | awk '{ print $1 }'";
    sha256 = execAndGetOutput(hash_cmd.c_str());
    sha256.erase(sha256.find_last_not_of(" \n\r\t") + 1);
  }
  catch (...)
  {
    throw ZCError(ZC_INTERNAL_ERROR, "Failed to calculate SHA-256 hash.");
  }

  fs::remove(archive_path);

  // Create recipe
  nlohmann::json recipe;
  recipe["name"] = lc_->name_;
  recipe["version"] = lc_->version_->string();
  recipe["url"] = archive_url;
  recipe["sha256"] = sha256;

  string file_path = "packages/" + lc_->name_ + "/" + lc_->version_->string() + ".json";

  string magic_link =
      "https://github.com/" GH_REPO "/new/main?filename=" + file_path + "&value=" + urlEncode(recipe.dump(2));

  log_(LogLevel::SUCCESS, "Hash verified: " + sha256);
  log_(LogLevel::INFO, "Your package is ready to be published!");
  log_(LogLevel::INFO, "To submit it to the global registry, simply click this link:");
  log_(LogLevel::INFO, U_BLUE + magic_link + COLOR_RESET);
  log_(LogLevel::INFO, "GitHub will automatically format your Pull Request.");
  log_(LogLevel::INFO, "Just scroll down and click 'Propose new file'!");
}

bool LocalController::addDependency(const std::string &target)
{
  GlobalController g(log_, force_);
  Package p;

  if (isInstalled(target) && !force_)
  {
    log_(LogLevel::WARNING, "Skipped package '" + target + "' already installed locally.");
    return false;
  }
  else
  {
    try
    {
      p = g.getPackage(target);
      p.is_installed_locally = false;
      r_->indexPackage(p);
      log_(LogLevel::SUCCESS, "Added dependency: " + p.name);
      return true;
    }
    catch (const ZCError &z)
    {
      log_(LogLevel::ERROR, "Skipped package '" + target + "' not installed globally.");
      return false;
    }
  }
}

void LocalController::checkFolderNames() const
{
  vector<string> invalid_names{"external", "build", ".cache", "CMakeLists.txt", "registry.json", "zc.json"};

  string src_str = lc_->src_folder_.filename().string();
  string inc_str = lc_->include_folder_.filename().string();

  bool is_src_invalid = ranges::find(invalid_names, src_str) != invalid_names.end();
  bool is_inc_invalid = ranges::find(invalid_names, inc_str) != invalid_names.end();

  if (is_src_invalid)
    throw ZCError(ZC_CONFIG_CONTENT_ERROR, "Source folder has a forbidden name");

  if (is_inc_invalid)
    throw ZCError(ZC_CONFIG_CONTENT_ERROR, "Include folder has a forbidden name");
}
